<?php

namespace App\Views;

use Core\Forms\Form;
use Core\View;

class HomeForm extends Form
{
    protected $data = [
        'attr' => [
            'method' => 'POST',
            'class' => 'createForm',
        ],
        'fields' => [
            'title' => [
                'type' => 'text',
                'label' => 'Title',
                'attr' => [
                    'placeholder' => 'pavadinimas',
                    'class' => 'title'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],
            'color' => [
                'type' => 'text',
                'label' => 'color',
                'attr' => [
                    'placeholder' => 'color',
                    'class' => 'color'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],
            'amount' => [
                'type' => 'number',
                'label' => 'amount',
                'attr' => [
                    'placeholder' => 'Amount',
                    'class' => 'amount'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],
            'price' => [
                'type' => 'number',
                'label' => 'price',
                'attr' => [
                    'placeholder' => 'Price',
                    'class' => 'price'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],
            'image' => [
                'type' => 'text',
                'label' => 'image',
                'attr' => [
                    'placeholder' => 'Image',
                    'class' => 'image'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],

        ],
        'buttons' => [
            'submit' => [
                'type' => 'submit',
                'value' => 'submit',
                'name' => 'action',
                'title' => 'Submit'
            ],
        ],

        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }


    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
