<?php

namespace App\Views;

use Core\Forms\Form;
use Core\View;

class LoginForm extends Form
{
    protected $data = [
        'attr' => [
            'method'=>'POST',
            'class'=>'loginForm',
        ],
        'fields' => [
            'email' => [
                'type' => 'email',
                'label' => 'Email',
                'attr' => [
                    'placeholder' => 'Emailas',
                    'class' => 'email'
                ],
                'validate' => [
                    'validate_not_empty',
                    'validate_email',
                    'validate_email_unique'
                ],
            ],
            'password' => [
                'type' => 'password',
                'label' => 'Slaptazodis',
                'attr' => [
                    'placeholder' => 'password',
                    'class' => 'password'
                ],
                'validate' => [
                    'validate_not_empty',
                    'validate_password'
                ],
            ],

        ],
        'buttons' => [
            'Login' => [
                'type' => 'submit',
                'value' => 'login',
                'name' => 'action',
                'title' => 'Login'
            ],
        ],
        'validators' => [
            'validate_fields_match' => [
                'password',

            ]
        ],
        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }


    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
