<?php

namespace App\Views;


use Core\View;

class ProductsTable extends View
{
    protected $data = [
        'productTable'=>'productTable'
        ];

    public function __construct()
    {
        parent::__construct($this->data);

    }


    public function render($templatePath = '')
    {
        return parent::render('../app/templates/productsTable.tpl.php'); // TODO: Change the autogenerated stub
    }
}