<?php

namespace App\Views;

use Core\Forms\Form;


class RegisterForm extends Form
{
    protected $data = [
        'attr' => [
         'method'=>'POST',
            'class'=>'registerForm'
        ],
        'fields' => [
            'full_name' => [
                'type' => 'text',
                'label' => 'Name',
                'attr' => [
                    'placeholder' => 'Vardas',
                    'class' => 'name'
                ],
                'validate' => [
                    'validate_not_empty',
                ],
            ],
            'email' => [
                'type' => 'email',
                'label' => 'Email',
                'attr' => [
                    'placeholder' => 'Emailas',
                    'class' => 'email'
                ],
                'validate' => [
                    'validate_not_empty',
                    'validate_email',
                    'validate_email_unique'
                ],
            ],
            'password' => [
                'type' => 'password',
                'label' => 'Slaptazodis',
                'attr' => [
                    'placeholder' => 'password',
                    'class' => 'password'
                ],
                'validate' => [
                    'validate_not_empty',
                    'validate_password'
                ],
            ],
            'password_repeat' => [
                'type' => 'password',
                'label' => 'Pakartokite slaptazodi',
                'attr' => [
                    'placeholder' => 'password',
                    'class' => 'password'
                ],
                'validate' => [
                    'validate_not_empty',
                ],
            ],
        ],
        'buttons' => [
            'Register' => [
                'type' => 'submit',
                'value' => 'register',
                'name' => 'action',
                'title'=>'Register'
            ],
        ],
        'validators' => [
            'validate_fields_match' => [
                'password',
                'password_repeat'
            ]
        ],
        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }


    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
